// <auto-generated />
using System;
using BackendIntegrationTest_Ameerhamza.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendIntegrationTest_Ameerhamza.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20241105161601_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendIntegrationTest_Ameerhamza.Model.CategoryDetails", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ParentCategoryId");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<int?>("TodoModelId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("category_Id");

                    b.HasIndex("TodoModelId");

                    b.ToTable("CategoryDetails", (string)null);
                });

            modelBuilder.Entity("BackendIntegrationTest_Ameerhamza.Model.TodoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Completed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Completed");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Location");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Priority");

                    b.Property<string>("Todo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Todo");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("todoTable", (string)null);
                });

            modelBuilder.Entity("BackendIntegrationTest_Ameerhamza.Model.CategoryDetails", b =>
                {
                    b.HasOne("BackendIntegrationTest_Ameerhamza.Model.TodoModel", null)
                        .WithMany("Category")
                        .HasForeignKey("TodoModelId");
                });

            modelBuilder.Entity("BackendIntegrationTest_Ameerhamza.Model.TodoModel", b =>
                {
                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
